### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Equals182** [Equals182/eqFTP#73]
**v0.7.0**
- [x] Comparing local and remote files for changes on opening local one
- [x] Comparing local and remote files for changes on opening REMOTE one
- [x] Sync on rename and delete
- [x] Sync on remote's rename and delete
- [x] Modal window appearing refactoring (don't redraw it etirely)
- [x] Rethink filetree redrawing (don't redraw it entirely)
- [x] Implement watching local project for changes and sync (for SCSS and stuff)
- [x] Add SFTP support
- [x] Add creating remote files and dirs
- [x] #68 Autochange connected server on change of local project.
- [x] Check directory for existence by CWD and PWD. Compare PWD result with expected directory.
- [x] Optional adding file to paused queue on save
- [x] Add progress in v0.7.0
- [ ] Add to ignore list by rightclick on local file

**Comment by Equals182** [comment]
fs.openSync
ENOENT

**Comment by Equals182** [comment]
Version for testing: https://github.com/Equals182/Buggy-eqFTP

**Comment by Equals182** [comment]
**Feature requests:**
- [ ] Sorting: When the user clicks on the down arrow it should switch to desc and click again to unsorted. When the user clicks on the upper arrow => asc then unsorted when the user clicks on the name you can make the current 3 toggle option.

**Comment by Equals182** [comment]
Bug:
```
[node-error 3:49:02 PM] [Launcher] uncaught exception at top level, exiting. TypeError: Cannot read property '0' of undefined
    at C:\Users\1\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\ftpDomain.js:2588:54
    at SFTP._parse (C:\Users\1\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\scp2\node_modules\ssh2\lib\SFTP\SFTPv3.js:1093:13)
    at ChannelStream.<anonymous> (C:\Users\1\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\scp2\node_modules\ssh2\lib\SFTP\SFTPv3.js:72:10)
    at ChannelStream.EventEmitter.emit (events.js:95:17)
    at ChannelStream.<anonymous> (_stream_readable.js:746:14)
    at ChannelStream.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at ChannelStream.Readable.push (_stream_readable.js:127:10)
    at Parser.<anonymous> (C:\Users\1\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\scp2\node_modules\ssh2\lib\Channel.js:106:25)
```
On changing project (and connecting to another server of course)

**Comment by Equals182** [comment]
Bug:
```
[node-error 10:34:37 AM] [Launcher] uncaught exception at top level, exiting. TypeError: Cannot read property 'progressReaded' of undefined
    at Client.eqFTPconnections.(anonymous function).listeners.progress (C:\Users\1\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\ftpDomain.js:685:65)
    at Client.EventEmitter.emit (events.js:106:17)
    at C:\Users\1\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\scp2\lib\client.js:207:18
    at callback (C:\Program Files (x86)\Brackets\www\extensibility\node\node_modules\fs-extra\node_modules\rimraf\node_modules\graceful-fs\polyfills.js:207:17)
    at Object.wrapper [as oncomplete] (fs.js:454:17)
```
SFTP. Upload event.

**Comment by Equals182** [comment]
```
[node-log 9:49:12 AM] [eqFTP-ftpDomain]: 1917: [q.a] Queue updated: {"a":[{"queue":"a","type":"file","connectionID":8,"direction":"download","localPath":"C:/Users/1/Desktop/Projects/service/tmpCheckDiff.eqFTPtmp","remotePath":"/functions/sanitizer.php","noTmp":true}],"p":[],"f":[],"s":[{"localPath":"C:/Users/1/Desktop/Projects/service/index.php","remotePath":"/index.php","name":"index.php","direction":"upload","sync":true,"queue":"s","type":"file","connectionID":8,"id":"f_1434350736225698","status":"QUEUE_TASK_STATUS_SUCCESS","ftpDomain":{"diff":{"check":false,"action":false}},"aRemotePath":"service/index.php","stats":{"dev":0,"mode":33206,"nlink":1,"uid":0,"gid":0,"rdev":0,"ino":0,"size":310,"atime":"2015-06-10T08:13:06.000Z","mtime":"2015-06-15T06:45:36.000Z","ctime":"2015-06-10T08:13:06.000Z"}}]}
/C:/Users/1/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:1629 Object
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 9:49:12 AM] [eqFTP-queueisbusy][q.p just started] Setting busy to true
/C:/Users/1/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:1629 Object
/C:/Users/1/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:1629 Object
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 9:49:12 AM] [eqFTP-ftpDomain]: [c.c] Connection already exists for this ID: 8
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 9:49:12 AM] [eqFTP-ftpDomain]: Trying to download file. Local path: C:/Users/1/Desktop/Projects/service/tmpCheckDiff.eqFTPtmp Remote path: service/functions/sanitizer.php
2extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 9:49:12 AM] [eqFTP-ftpDomain]: [c.c] Connection already exists for this ID: 8
extensions/default/DebugCommands/NodeDebugUtils.js:114 [node-error 9:49:12 AM] [Launcher] uncaught exception at top level, exiting. TypeError: Cannot read property '0' of undefined
    at C:\Users\1\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\ftpDomain.js:2685:54
    at SFTP._parse (C:\Users\1\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\scp2\node_modules\ssh2\lib\SFTP\SFTPv3.js:1093:13)
    at ChannelStream.<anonymous> (C:\Users\1\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\scp2\node_modules\ssh2\lib\SFTP\SFTPv3.js:72:10)
    at ChannelStream.EventEmitter.emit (events.js:95:17)
    at ChannelStream.<anonymous> (_stream_readable.js:746:14)
    at ChannelStream.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at ChannelStream.Readable.push (_stream_readable.js:127:10)
    at Parser.<anonymous> (C:\Users\1\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\scp2\node_modules\ssh2\lib\Channel.js:106:25)extensions/default/DebugCommands/NodeDebugUtils.js:114 handleLogEvent
extensions/default/DebugCommands/NodeDebugUtils.js:114 [node-info 9:49:12 AM] [Server] stopping
/filesystem/FileSystem.js:957 File watchers went offline!
9/utils/NodeConnection.js:89 WebSocket connection to 'ws://localhost:51177/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
/C:/Users/1/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:1580 9:49:25.85 Adding to queue Object
/utils/EventDispatcher.js:224 Exception in 'change' listener on FileSystem TypeError: Cannot read property 'addToQueue' of undefined TypeError: Cannot read property 'addToQueue' of undefined
    at Object.<anonymous> (file:///C:/Users/1/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:1581:49)
    at Function.n.extend.each (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:2882)
    at Object.eqFTP.ftp.queue.add (file:///C:/Users/1/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:1574:19)
    at file:///C:/Users/1/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:3333:57
    at String.<anonymous> (file:///C:/Users/1/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:1104:41)
    at Function.n.extend.each (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:2882)
    at file:///C:/Users/1/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:1098:27
    at Object.eqFTP.sf.settings.read (file:///C:/Users/1/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:1068:25)
    at Object.eqFTP.sf.connections.getByPath (file:///C:/Users/1/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:1094:35)
    at file:///C:/Users/1/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:3316:42
/utils/EventDispatcher.js:225 Assertion failed:
/C:/Users/1/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:3260 9:49:25.102 [eqFTP-uploadonsave] documentSaved triggered
/C:/Users/1/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:3262 [eqFTP-uploadonsave] Checking if file is within project C:/Users/1/Desktop/Projects/service/functions/sanitizer.php
/C:/Users/1/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:3264 [eqFTP-uploadonsave] Yes it is
/C:/Users/1/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:3266 [eqFTP-uploadonsave] Getting connection ID by path
/C:/Users/1/AppData/Roaming/Brackets/extensions/user/equals182.eqftp/main.js:3268 [eqFTP-uploadonsave] Here it is:  8
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 9:49:26 AM] [eqFTP-ftpDomain] Loaded
/filesystem/FileSystem.js:965 Watching disabled for C:/Users/1/Desktop/Projects/service/
/project/ProjectManager.js:776 Error unwatching project root:  C:/Users/1/Desktop/Projects/service/ RootNotBeingWatched
```

**Comment by Equals182** [comment]
```
 [node-error 2:13:08 PM] [eqFTP-ftpDomain]: 2332: [f.d] There was an error downloading the file.
NodeDebugUtils.js:114 [node-error 2:13:08 PM] [eqFTP-ftpDomain]: 2333: [f.d][FTP-error] {"code":550,"text":"550 Failed to open file.","isMark":false,"isError":true}
NodeDebugUtils.js:117 [node-log 2:13:08 PM] [eqFTP-queueisbusy][q.p file] Setting busy to false
NodeDebugUtils.js:117 [node-log 2:13:08 PM] [eqFTP-ftpDomain]: [q.m] Moving in queue with params: {"connectionID":0,"from":"a","to":"f","files":[{"queue":"a","type":"file","connectionID":0,"direction":"download","localPath":"C:/Users/1/Desktop/Projects/stones/tmpCheckDiff.eqFTPtmp","remotePath":"/public_html/index — копия.php","noTmp":true,"status":550,"ftpDomain":{"diff":{"check":false,"action":false}},"aRemotePath":"/public_html/index — копия.php","stats":{"size":0},"size":"0"}]}
main.js:1644 Object
main.js:1644 Object
NodeDebugUtils.js:117 [node-log 2:13:08 PM] [eqFTP-ftpDomain]: [q.p] Queue is empty
NodeDebugUtils.js:117 [node-log 2:13:08 PM] [eqFTP-ftpDomain]: Disconnecting...
main.js:1644 Object
NodeDebugUtils.js:117 [node-log 2:13:08 PM] [TEST-ECONNRESET] Have client
NodeDebugUtils.js:117 [node-log 2:13:08 PM] [TEST-ECONNRESET] Removing listeners
NodeDebugUtils.js:117 [node-log 2:13:08 PM] [TEST-ECONNRESET] Listeners removed
NodeDebugUtils.js:117 [node-log 2:13:08 PM] [eqFTP-ftpDomain]: [c.c] ftpDomain currently disconnecting from: 0
NodeDebugUtils.js:117 [node-log 2:13:08 PM] [TEST-ECONNRESET] Abort performed
NodeDebugUtils.js:117 [node-log 2:13:08 PM] [eqFTP-ftpDomain]: [c.c] ftpDomain currently disconnecting from: 0
NodeDebugUtils.js:117 [node-log 2:13:08 PM] [TEST-ECONNRESET] Quit performed
NodeDebugUtils.js:117 [node-log 2:13:08 PM] [eqFTP-queueisbusy][c.d just diconnected properly] Setting busy to false
NodeDebugUtils.js:117 [node-log 2:13:08 PM] [eqFTP-ftpDomain]: Disonnected.
main.js:1644 Object
main.js:1859 [eqFTP] Disconnected from server
NodeDebugUtils.js:117 [node-log 2:13:08 PM] [eqFTP-ftpDomain]: Connecting to this ID: 0
main.js:1644 Object
NodeDebugUtils.js:117 [node-log 2:13:08 PM] [eqFTP-ftpDomain]: Connecting...
NodeDebugUtils.js:117 [node-log 2:13:08 PM] [eqFTP-ftpDomain]: [s.a] Client is already authorized for connection ID: 0
NodeDebugUtils.js:117 [node-log 2:13:08 PM] [eqFTP-ftpDomain]: [s.gRR] Getting remote root for this ID: 0
main.js:1644 Object
NodeDebugUtils.js:117 [node-log 2:13:08 PM] [eqFTP-ftpDomain]: [q.p] Queue is empty
main.js:1644 Object
main.js:1920 [eqFTP] Connected to server
NodeDebugUtils.js:117 [node-log 2:13:08 PM] [eqFTP-ftpDomain]: Connected...
NodeDebugUtils.js:117 [node-log 2:13:08 PM] [eqFTP-rawTest] start
NodeDebugUtils.js:117 [node-log 2:13:08 PM] [eqFTP-rawTest] step 2
NodeDebugUtils.js:117 [node-log 2:13:08 PM] [eqFTP-rawTest] Command string:  user mts9235253_spb
NodeDebugUtils.js:117 [node-log 2:13:08 PM] [eqFTP-rawTest] Pushing to queue:  { command: 'user mts9235253_spb',
  callback: [Function],
  callback100: undefined }
NodeDebugUtils.js:117 [node-log 2:13:08 PM] [eqFTP-rawTest] Queue is:  [ { command: { cmd: 'placeholder' }, callback: [Function] },
  { command: 'user mts9235253_spb',
    callback: [Function],
    callback100: undefined } ]
NodeDebugUtils.js:117 [node-log 2:13:08 PM] [eqFTP-rawTest] doing queue
NodeDebugUtils.js:114 [node-error 2:13:08 PM] [Launcher] uncaught exception at top level, exiting. TypeError: Object #<Object> has no method 'replace'
    at Ftp.doQueue (C:\Users\1\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\jsftp\lib\jsftp.js:228:70)
    at Ftp.raw (C:\Users\1\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\jsftp\lib\jsftp.js:221:14)
    at Ftp.auth (C:\Users\1\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\jsftp\lib\jsftp.js:118:10)
    at Object._commands.service.auth (C:\Users\1\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\ftpDomain.js:803:84)
    at Object._commands.connection.createClient.callback (C:\Users\1\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\ftpDomain.js:387:59)
    at eqFTPconnections.(anonymous function).listeners.connect (C:\Users\1\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\ftpDomain.js:748:44)
    at EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (C:\Users\1\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\jsftp\lib\jsftp.js:91:14)
    at Socket.EventEmitter.emit (events.js:117:20)
    at Object.afterConnect [as oncomplete] (net.js:883:10)
NodeDebugUtils.js:114 [node-info 2:13:08 PM] [Server] stopping
/filesystem/FileSystem.js:957 File watchers went offline!
main.js:1595 14:13:9.637 Adding to queue Object
4/utils/NodeConnection.js:89 WebSocket connection to 'ws://localhost:51973/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
/filesystem/FileSystem.js:965 Watching disabled for C:/Users/1/Desktop/Projects/stones/
5/utils/NodeConnection.js:89 WebSocket connection to 'ws://localhost:51973/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
NodeDebugUtils.js:117 [node-log 2:13:19 PM] [eqFTP-ftpDomain] Loaded
```

**Comment by Equals182** [comment]
```
[node-error 11:38:03 AM] [Launcher] uncaught exception at top level, exiting. TypeError: Object #<Object> has no method 'replace'
    at Ftp.doQueue (C:\Users\1\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\jsftp\lib\jsftp.js:228:70)
    at Ftp.raw (C:\Users\1\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\jsftp\lib\jsftp.js:221:14)
    at Ftp.auth (C:\Users\1\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\jsftp\lib\jsftp.js:118:10)
    at Object._commands.service.auth (C:\Users\1\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\ftpDomain.js:803:84)
    at Object._commands.connection.createClient.callback (C:\Users\1\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\ftpDomain.js:387:59)
    at eqFTPconnections.(anonymous function).listeners.connect (C:\Users\1\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\ftpDomain.js:748:44)
    at EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (C:\Users\1\AppData\Roaming\Brackets\extensions\user\equals182.eqftp\node\node_modules\jsftp\lib\jsftp.js:91:14)
    at Socket.EventEmitter.emit (events.js:117:20)
    at Object.afterConnect [as oncomplete] (net.js:883:10)
```
